# Q3

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

In [38]:
X = pd.read_csv("LR_data//X.csv")
Y = pd.read_csv("LR_data//Y.csv")
reg = LinearRegression().fit(X, Y)

In [39]:
print(reg.intercept_)
reg.coef_

[-0.99990689]


array([[1.2003912 , 2.10019033, 2.19850545]])

## ANS : -1,1.2,2.1,2.2

# Q4

In [12]:
from sklearn.linear_model import Ridge

In [14]:
for i in range(1,11):
    clf = Ridge(alpha=i)
    clf.fit(X, Y)
    print(clf.coef_)

[[1.1869763  2.07552201 2.17124348]]
[[1.17385737 2.05142773 2.14464842]]
[[1.16102475 2.02788762 2.11869614]]
[[1.14846919 2.00488276 2.09336362]]
[[1.13618183 1.98239505 2.06862897]]
[[1.12415418 1.96040722 2.04447128]]
[[1.11237812 1.93890274 2.02087062]]
[[1.10084583 1.91786582 1.99780797]]
[[1.08954985 1.89728135 1.97526515]]
[[1.078483   1.87713486 1.95322481]]


## ANS: Decrease

# Q5

In [17]:
iris_x = pd.read_csv("iris//irisX.csv")
iris_y = pd.read_csv("iris//irisY.csv")

In [27]:
training_x = iris_x[:100] # 100 rows, 3 features
training_x = training_x.iloc[:,:3]
testing_x = iris_x[100:]
testing_x = testing_x.iloc[:,:3]
training_y = iris_y[:100]
testing_y = iris_y[100:]

In [28]:
from sklearn.linear_model import LogisticRegression

In [31]:
clf = LogisticRegression(C= 10000, penalty= "l2")
clf.fit(training_x,training_y)
clf.score(testing_x,testing_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9795918367346939

## ANS : 98

# Q6

In [32]:
from sklearn.svm import SVC

In [41]:
C = [0.01,1,10]
for c in C:
    clf = SVC(gamma = 0.5,C = c)
    clf.fit(training_x,training_y)
    print(clf.score(testing_x,testing_y),sum(clf.n_support_))
    

0.30612244897959184 100
0.9795918367346939 41
0.9795918367346939 32


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## ans : 98 and 41