# Q3

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

In [19]:
X = pd.read_csv("LR_data//X.csv",header = None)
Y = pd.read_csv("LR_data//Y.csv",header = None)
reg = LinearRegression().fit(X, Y)

In [20]:
print(reg.intercept_)
reg.coef_

[-0.99991166]


array([[1.20039321, 2.10019422, 2.19850758]])

## ANS : -1,1.2,2.1,2.2

# Q4

In [5]:
from sklearn.linear_model import Ridge

In [6]:
for i in range(1,11):
    clf = Ridge(alpha=i)
    clf.fit(X, Y)
    print(clf.coef_)

[[1.18702759 2.07562096 2.17129761]]
[[1.17395574 2.05161733 2.14475207]]
[[1.16116811 2.02816372 2.11884694]]
[[1.14865555 2.00524139 2.09355934]]
[[1.1364093  1.98283245 2.06886748]]
[[1.12442096 1.96091982 2.04475058]]
[[1.11268248 1.93948715 2.0211888 ]]
[[1.10118616 1.91851881 1.99816322]]
[[1.08992458 1.89799986 1.97565576]]
[[1.07889065 1.87791596 1.95364913]]


## ANS: Decrease

# Q5

In [21]:
iris_x = pd.read_csv("iris//irisX.csv",header = None)
iris_y = pd.read_csv("iris//irisY.csv",header = None)

In [25]:
training_x = iris_x[:100] # 100 rows, 3 features
training_x = training_x.iloc[:,:3]
testing_x = iris_x[100:]
testing_x = testing_x.iloc[:,:3]
training_y = iris_y[:100]
testing_y = iris_y[100:]

In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
clf = LogisticRegression(C= 10000, penalty= "l2")
clf.fit(training_x,training_y)
clf.score(testing_x,testing_y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.98

## ANS : 98

# Q6

In [31]:
from sklearn.svm import SVC
from sklearn.multiclass import OneVsRestClassifier

In [33]:
C = [0.01,1,10]
for c in C:
    clf = OneVsRestClassifier(SVC(gamma = 0.5,C = c))
    clf.fit(training_x,training_y)
    print(clf.score(testing_x,testing_y))
    

0.98
0.98
0.98


## ans : 98 and 41